version: "3.7"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - faktura-db:/var/lib/postgresql/data

  faktura:
    build:
      context: .
    environment:
      DB_SCHEMA: postgres
      DB_USER: postgres
      DB_PASSWORD: g17cKM19Cuovgt7a
      DB_HOST: /cloudsql/faktura-312905:europe-north1:faktura-db
    depends_on:
      - postgres
    ports:
      - '3000:3000'

volumes:
  faktura-db: